### ISSUE TITLE
App became unusable / crashes while using netrw

### ISSUE THREAD

**Issue by goerz** [holzschu/iVim#4]
At some point in the last couple of months, my installation of iVim (still the exact same one I compiled back in February) became unusable. I tried deleting and recompiling the app. Compilation works, but I'm still seeing the same behavior: external commands hangs, opening some files hangs, and when I try to use netrw (:e .), I get the following:

![screenshot](https://user-images.githubusercontent.com/112306/47523528-432bae00-d866-11e8-9a8c-d1e408b1241f.png)

The app then crashes after some time. Since I did this while connected to Xcode, it showed me where the problem seems to be:

![screenshot_2018-10-25_14 51 52_6iqxr3](https://user-images.githubusercontent.com/112306/47523606-70785c00-d866-11e8-8dd7-fdaa84e93602.png)

Note that this is immediately after compiling iVim, that is, without any configuration or data.

I'm not seeing this problem with the app store version of iVim.

Oh, one thing seemed to go wrong during the compilation, while I execute the `get_frameworks.sh` script:

~~~
...
Compiling libffi-3.2.1:
warning: The iOS deployment target is set to 5.0, but the range of supported deployment target versions for this platform is 8.0 to 12.0. (in target 'libffi-iOS')
checking build system type... i386-apple-darwin17.7.0
checking host system type... i386-apple-darwin11
checking target system type... i386-apple-darwin11
checking for gsed... sed
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for i386-apple-darwin11-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... ../install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for i386-apple-darwin11-gcc... xcrun -sdk iphonesimulator clang -arch i386
checking whether the C compiler works... no
configure: error: in `/Users/goerz/iVimWorkdir/python_ios/libffi-3.2.1/build_iphonesimulator-i386':
configure: error: C compiler cannot create executables
See `config.log' for more details
Traceback (most recent call last):
  File "generate-darwin-source-and-headers.py", line 209, in <module>
    generate_source_and_headers(generate_osx=not args.only_ios, generate_ios=not args.only_osx)
  File "generate-darwin-source-and-headers.py", line 188, in generate_source_and_headers
    build_target(simulator_platform, platform_headers)
  File "generate-darwin-source-and-headers.py", line 149, in build_target
    subprocess.check_call(['../configure', '-host', platform.triple], env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../configure', '-host', 'i386-apple-darwin11']' returned non-zero exit status 77
note: Using new build systemnote: Planning buildnote: Constructing build description
** BUILD FAILED **
...
~~~

I don't know if this has to do with anything (but again, I first observed the problem with the version of iVim that I compiled in February, and which ran without problems for a while). I would assume that some iOS update might have triggered something.

Any ideas?

**Comment by goerz** [comment]
Regarding external commands: When I do e.g. `:!grep`, the Xcode console shows this message:

~~~
Failed loading grep from text.framework/text, cause = dlopen(text.framework/text, 9): image not found
Failed loading grep from text.framework/text, cause = invalid handle passed to dlsym()
grep: command not found
~~~

Similar messages for any other command (e.g. `tar`)

**Comment by goerz** [comment]
Still failing after upgrading my Mac to Mojave and recompiling. Another things that fails in the compiled app, but works in the App-Store version, is to source a vimball. It hangs again in the `waitforChars` function (based on what I see when I hit the pause button in Xcode)

**Comment by holzschu** [comment]
I'm going to have a look. 
The "dlopen(text.framework/text, 9): image not found" would point to a framework not being embedded. You would need to check the list of embedded frameworks. 

The `libffi-3.2.1` issue: I guess the script that compiles `libffi` has hardcoded the iOS SDK version, and complains that it can't find the proper SDK.

**Comment by holzschu** [comment]
Update: I can reproduce the `libffi` issue. Probably something related to the latest version of Xcode. I'm working on a fix.

**Comment by goerz** [comment]
Thanks, Nicolas! Are you currently able to run the iVim fork on iOS12 without problems? I think that may have been the update that caused all of this strange behavior.

**Comment by holzschu** [comment]
So, I've merged with the master branch, edited a few things, recompiled, and the app appears to be running. I've committed all my changes. Let me know if the problems persist.

**Comment by goerz** [comment]
The `get_frameworks.sh` script now runs without error, but compilation of iVim in Xcode fails:

![image](https://user-images.githubusercontent.com/112306/47620667-13c5ad00-dac3-11e8-8e2d-c01c74dd269a.png)

**Comment by holzschu** [comment]
Ah, yes, that's vimproc, a component for VimShell. I shouldn't have left it. I've removed it; iVim should compile now.

**Comment by goerz** [comment]
Same thing with error msg `/Users/goerz/iVimWorkdir/iVim/Frameworks/libnetwork_ios.dylib: No such file or directory` now.

Are all the embedded binaries greyed out in the screenshot below missing? (seems not: there's corresponding files in the `iVim/Frameworks` folder)

![image](https://user-images.githubusercontent.com/112306/47621825-c6057080-dad3-11e8-9125-4e137b9c85d1.png)

I tried removing `libnetwork` from that list, but then compilation fails with `/Users/goerz/iVimWorkdir/iVim/Frameworks/libcrypto.a: No such file or directory` (which isn't even in the list)

**Comment by holzschu** [comment]
Well spotted! `libnetwork_ios.dylib` was replaced with `network_ios.framework` (and should have been removed earlier). `libcrypto.a` comes from `libssh2`. It doesn't appear to be needed, though.

I've removed both, does it compile now?

**Comment by goerz** [comment]
Compilation works perfectly now, and even more importantly, this has fixed the problem that I was having. Thanks for you help!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
